version: '3.8'

services:
  dashboard:
    build: . # tag1534/glass-dashboard:latest   Or 'build: .' if you are building locally
    container_name: glass-dashboard
    ports:
      - "8085:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - TRUENAS_IP=${TRUENAS_IP}
      - TRUENAS_API_KEY=${TRUENAS_API_KEY}
      - PROXMOX_URL=${PROXMOX_URL}
      - PROXMOX_NODE=${PROXMOX_NODE}
      - PROXMOX_TOKEN_ID=${PROXMOX_TOKEN_ID}
      - PROXMOX_TOKEN_SECRET=${PROXMOX_TOKEN_SECRET}
      - PROCFS_PATH=/host/proc
    pid: "host"
    network_mode: "bridge"
    restart: always
